

mod_id=enchantingrunes
curse_slug=runes
curse_id=493759
mod_version=1.0.1
mod_name=enchantingrunes
mod_group_id=com.lothrazar.enchantingrunes
mod_license=SeeGithub
mod_authors=Lothrazar
mod_description=mod
modrinth_id=

flib_version=0.1.0
flib_file=8022223


